// Autogenerated `SwiftReflector` @ 2015-08-02 20:03:13 +0000

import Foundation

// PersonalityType

// Equatable PersonalityType

extension PersonalityType  { 
}

func == (lhs: PersonalityType, rhs: PersonalityType) -> Bool { 
    return lhs.isFun == rhs.isFun
        && lhs.isSafeFlyer == rhs.isSafeFlyer
        && lhs.isAlphaDuck == rhs.isAlphaDuck
}

// Hashable PersonalityType

extension PersonalityType  { 
    var hashValue: Int { 
        return isFun.hashValue
        ^ isSafeFlyer.hashValue
        ^ isAlphaDuck.hashValue
    }
}



